<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue';
import QRCode from 'qrcode';
import Hls from 'hls.js';
type Library={id:number;name:string;roots:string[];intervalMinutes:number;lastScan:number};
type Video={id:number;libraryId:number;title:string;path:string;size:number;mtime:number;created:number;duration:number;position:number;favorite:boolean;metadata:any};
const state=ref<'loading'|'setup'|'login'|'app'>('loading'), password=ref(''), code=ref(''), secret=ref(''), setupURL=ref(''), error=ref(''), libraries=ref<Library[]>([]), selected=ref<number>(0), videos=ref<Video[]>([]), search=ref(''), sort=ref('title'), direction=ref('asc'), favoriteOnly=ref(false), current=ref<Video|null>(null), videoURL=ref(''), job=ref<any>(null), showInfo=ref(false), showLibrary=ref(false), newName=ref(''), newRoots=ref<string[]>([]), newRoot=ref(''), timer=ref(0), timerHandle=ref<number|undefined>(), qr=ref(''), videoEl=ref<HTMLVideoElement|null>(null), hls=ref<Hls|null>(null);
async function api(path:string,options:RequestInit={}){options.headers={...(options.headers||{}),'X-Requested-With':'nas-video','Content-Type':'application/json'};const r=await fetch(path,options);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'请求失败');return d}
async function refreshAuth(){const d=await api('/api/auth');state.value=d.initialized?(d.authenticated?'app':'login'):'setup';if(state.value==='app')await loadLibraries()}
async function setup(){try{if(!secret.value){const d=await api('/api/setup',{method:'POST',body:JSON.stringify({password:password.value})});secret.value=d.secret;setupURL.value=d.url;qr.value=await QRCode.toDataURL(d.url,{width:220});return}await api('/api/setup',{method:'POST',body:JSON.stringify({password:password.value,code:code.value})});await refreshAuth()}catch(e:any){error.value=e.message}}
async function login(){try{await api('/api/login',{method:'POST',body:JSON.stringify({password:password.value,code:code.value})});await refreshAuth()}catch(e:any){error.value=e.message}}
async function loadLibraries(){libraries.value=await api('/api/libraries');if(!selected.value&&libraries.value.length)selected.value=libraries.value[0].id;await loadVideos()}
async function loadVideos(){if(!selected.value){videos.value=[];return};const p=new URLSearchParams({library:String(selected.value),q:search.value,sort:sort.value,direction:direction.value});if(favoriteOnly.value)p.set('favorite','1');videos.value=(await api('/api/videos?'+p)).items}
async function saveLibrary(){try{await api('/api/libraries',{method:'POST',body:JSON.stringify({name:newName.value,roots:newRoots.value,intervalMinutes:360})});newName.value='';newRoots.value=[];showLibrary.value=false;await loadLibraries()}catch(e:any){error.value=e.message}}
async function addRoot(){if(newRoot.value&&!newRoots.value.includes(newRoot.value))newRoots.value.push(newRoot.value);newRoot.value=''}
function fmt(n:number){if(!n)return '—';if(n<3600)return new Date(n*1000).toISOString().substring(14,19);return new Date(n*1000).toISOString().substring(11,19)}
function bytes(n:number){return n>1073741824?(n/1073741824).toFixed(1)+' GB':n>1048576?(n/1048576).toFixed(1)+' MB':(n/1024).toFixed(0)+' KB'}
async function play(v:Video){current.value=v;showInfo.value=false;job.value=null;timer.value=0;try{const d=await api('/api/play',{method:'POST',body:JSON.stringify({videoId:v.id,mode:'auto',stopAfter:0})});videoURL.value=d.url;if(d.jobId){job.value={id:d.jobId,mode:'starting'};pollJob(d.jobId)};await api('/api/videos/'+v.id+'/progress',{method:'POST',body:JSON.stringify({position:v.position||0})})}catch(e:any){error.value=e.message}}
async function pollJob(id:string){const d=await api('/api/jobs/'+id);job.value=d;if(!d.done)setTimeout(()=>pollJob(id),1500)}
async function saveProgress(){if(current.value){await api('/api/videos/'+current.value.id+'/progress',{method:'POST',body:JSON.stringify({position:(document.querySelector('video') as HTMLVideoElement)?.currentTime||0})})}}
async function randomNext(){if(!selected.value)return;try{const d=await api('/api/random?library='+selected.value);if(d.video)play(d.video)}catch{} }
function setTimer(){clearTimeout(timerHandle.value);if(timer.value>0)timerHandle.value=window.setTimeout(()=>{const el=document.querySelector('video') as HTMLVideoElement|null;el?.pause();if(job.value)api('/api/jobs/'+job.value.id,{method:'DELETE'}).catch(()=>{})},timer.value*60000)}
watch(videoURL,()=>{if(!videoEl.value||!videoURL.value)return;hls.value?.destroy();if(videoURL.value.endsWith('.m3u8')&&Hls.isSupported()){const x=new Hls({enableWorker:true});x.loadSource(videoURL.value);x.attachMedia(videoEl.value);hls.value=x}else{videoEl.value.src=videoURL.value}videoEl.value.onloadedmetadata=()=>{if(current.value?.position)videoEl.value!.currentTime=current.value.position;videoEl.value!.play().catch(()=>{})}});watch([selected,search,sort,direction,favoriteOnly],loadVideos);onMounted(refreshAuth);
</script>
<template>
<main class="shell" v-if="state==='loading'"><div class="card">正在加载…</div></main>
<main class="shell" v-else-if="state==='setup'||state==='login'"><section class="card auth"><h1>NAS Video</h1><p>{{state==='setup'?'首次使用，请设置密码并绑定 TOTP':'请输入密码和全局 TOTP 验证码'}}</p><input v-model="password" type="password" placeholder="密码（至少 10 位）"><input v-model="code" inputmode="numeric" placeholder="TOTP 验证码"><div v-if="state==='setup'&&secret" class="totp"><img v-if="qr" :src="qr"><code>{{secret}}</code><small>请在验证器中添加此密钥，然后输入验证码完成初始化。</small></div><button @click="state==='setup'?setup():login()">{{state==='setup'?(secret?'完成初始化':'生成 TOTP'): '登录'}}</button><p class="error">{{error}}</p></section></main>
<main class="app" v-else><header><strong>NAS Video</strong><select v-model="selected"><option :value="0">选择媒体库</option><option v-for="l in libraries" :value="l.id">{{l.name}}</option></select><button @click="showLibrary=true">添加媒体库</button><button @click="api('/api/scan',{method:'POST'})">扫描</button><button @click="api('/api/logout',{method:'POST'}).then(refreshAuth)">退出</button></header><section class="toolbar"><input v-model="search" placeholder="搜索视频"><select v-model="sort"><option value="title">标题</option><option value="created">创建时间</option><option value="modified">修改时间</option><option value="duration">时长</option><option value="size">文件大小</option></select><button @click="direction=direction==='asc'?'desc':'asc'">{{direction==='asc'?'升序':'降序'}}</button><button :class="{active:favoriteOnly}" @click="favoriteOnly=!favoriteOnly">收藏夹</button></section><section class="grid"><article v-for="v in videos" :key="v.id" class="video-card" @click="play(v)"><div class="thumb"><img :src="`/api/videos/${v.id}/preview?t=0`" loading="lazy"><span>{{fmt(v.duration)}}</span></div><b>{{v.title}}</b><small>{{bytes(v.size)}} · {{v.position>0?fmt(v.position)+' 已观看':''}}</small><button class="star" @click.stop="api('/api/videos/'+v.id+'/favorite',{method:'POST',body:JSON.stringify({favorite:!v.favorite})}).then(loadVideos)">{{v.favorite?'★':'☆'}}</button></article></section><p v-if="!videos.length" class="empty">此媒体库暂无视频</p>
<div v-if="current" class="player"><div class="player-top"><button @click="current=null">关闭</button><b>{{current.title}}</b><button @click="showInfo=!showInfo">信息</button></div><video ref="videoEl" controls autoplay @timeupdate="saveProgress" @ended="randomNext"><track kind="subtitles" label="字幕" srclang="zh" :src="`/api/videos/${current.id}/subtitle?stream=0`"></video><div class="player-controls"><label>停止：<input v-model.number="timer" type="number" min="0" placeholder="分钟" @change="setTimer"> 分钟</label><button @click="randomNext">随机播放下一个</button></div><div v-if="job||showInfo" class="info"><p v-if="job">转码：{{job.mode||'准备中'}} {{job.message||''}} {{job.error||''}}</p><template v-if="showInfo"><p>文件：{{current.path}}</p><p>大小：{{bytes(current.size)}}　时长：{{fmt(current.duration)}}</p><p>创建时间：{{current.created?new Date(current.created*1000).toLocaleString():'不可用'}}</p><p>修改时间：{{new Date(current.mtime*1000).toLocaleString()}}</p></template></div></div>
<div v-if="showLibrary" class="modal"><section class="card"><button class="close" @click="showLibrary=false">×</button><h2>添加媒体库</h2><input v-model="newName" placeholder="媒体库名称"><div class="roots"><input v-model="newRoot" placeholder="映射目录绝对路径"><button @click="addRoot">添加路径</button></div><p v-for="r in newRoots">{{r}}</p><button @click="saveLibrary">保存</button></section></div>
</main></template>
